### ISSUE TITLE
This wont work for real GT

### ISSUE THREAD

**Issue by playingoDEERUX** [teocoder/enet-socks5#1]
Real GT nowadays requires you to join their **https website (WITH THE SOCKS5 ENDPOINT)** as well, and because all the implementation is only in enet itself, within the C code, unlike my implementation where I have a sockstunnel class separated so that I can still do more further on with the socks connection (such as joining the webserver first to avoid getting shadowbanned), this marks yet another giant superiority in my implementation.

My implementation outperforms this repo and Olli's implementation (recently published on github) massively in especially 5 aspects:

1. The fact that my implementation has an actual framework
2. My implementation has a very high-performance, extremely multithreaded, multi-clustered architecture
3. My implementation has custom ENet tweaks (such as lower ping frequency to save bandwidth & CPU), other optimizations
4. My implementation allows for more than 1024 sockets to be opened (go try yourself and you will see what I mean), that's because I make use of poll() instead of the default select() in ENet, select() only allows for 3 bits of data per file descriptor, meaning you should get segmentation faults when trying to spawn more than 1024 bots. With my implementation, you can go **full 64K (32K for udp, and 32k for the socks5 tcp implementation)**

5. Lastly, my implementation actually works up-to-date because you will get shadowbans on THIS as opposed to mine because you dont visit the webserver before to 1. grab meta and 2. making a request to growtopia1.com/growtopia2.com is necessary to avoid shadowbans, and you can't easily do it in your implementation because your socks5 stuff isn't separated, it is embedded right into ENet itself which doesn't really give much headroom to do anything else from within the socks5 connection, to get its proxy IP on the webserver and not your own local ip as if you were to visit the page normally.

![image](https://user-images.githubusercontent.com/62474734/188581809-80db5252-e699-4cfc-98ea-6ec0da635e1f.png)
![image](https://user-images.githubusercontent.com/62474734/188581835-38e3cdd4-8021-4fa5-b1eb-70fc93589d38.png)

**Comment by teocoder** [comment]
nothing is stopping you from making the https request with the proxy and as of now it is not even needed. thanks for mentioning this 1024 socket limit tho, i will fix it when i get home. but i think our is still better because our uses non-blocking sockets so you dont have to sleep the whole thread to connect to all of the proxies and i think its lot easier for people just to replace their enet with this single header enet instead of copying all of those files in your repository

**Comment by playingoDEERUX** [comment]
GTPS3 needs this but I mean the 1024 socket limit is an easy fix, I already told kevz and others to fix it w/ USE_POLL definition, still there are 4 other aspects that make this inferior

**Comment by playingoDEERUX** [comment]
My implementation could scale to beyond 64K, technically to unlimited if u have enough money to buy multiple machines/vps's as it's multi-clustered IPC, so using my stuff you could e.g mirror 1 chat message to even a million other bots which is due to its scalability, because I don't simply have a socks5 on top of it - You'll notice I've made a whole botting suite & network when you take a look at my work

**Comment by AboodTBR** [comment]
> GTPS3 needs this but I mean the 1024 socket limit is an easy fix, I already told kevz and others to fix it w/ USE_POLL definition, still there are 4 other aspects that make this inferior

you didn't tell us shit, we discovered it ourselves and why do you hold alot of pride in that? it's not a hard thing to find.

**Comment by teocoder** [comment]
"The fact that my implementation has an actual framework", ok and? this isnt some gt bot repository, just enet socks5 with simple enet client for gt


"My implementation has a very high-performance, extremely multithreaded, multi-clustered architecture", i dont see how this is lower performance than yours, could you show or tell proof about this?

"Lastly, my implementation actually works up-to-date because you will get shadowbans on THIS as opposed to mine because you dont visit the webserver before to 1. grab meta and 2. making a request to growtopia1.com/growtopia2.com is necessary to avoid shadowbans", this doesn't give shadow bans and uhh you can just make the https request with the same proxy if you want to.



+ you are fucking weird, you said u quit gt and now writing some essays trying to prove you're the best, grow up...

**Comment by playingoDEERUX** [comment]
> > GTPS3 needs this but I mean the 1024 socket limit is an easy fix, I already told kevz and others to fix it w/ USE_POLL definition, still there are 4 other aspects that make this inferior
> 
> you didn't tell us shit, we discovered it ourselves and why do you hold alot of pride in that? it's not a hard thing to find.
i dont care, fact is u didnt use poll before and I already had it and said it out loud in my implementation.

**Comment by playingoDEERUX** [comment]
> "The fact that my implementation has an actual framework", ok and? this isnt some gt bot repository, just enet socks5 with simple enet client for gt
> 
> "My implementation has a very high-performance, extremely multithreaded, multi-clustered architecture", i dont see how this is lower performance than yours, could you show or tell proof about this?
> 
> "Lastly, my implementation actually works up-to-date because you will get shadowbans on THIS as opposed to mine because you dont visit the webserver before to 1. grab meta and 2. making a request to growtopia1.com/growtopia2.com is necessary to avoid shadowbans", this doesn't give shadow bans and uhh you can just make the https request with the same proxy if you want to.
> 
> * you are fucking weird, you said u quit gt and now writing some essays trying to prove you're the best, grow up...

maybe I cant quit if I get further provocation from this:
![image](https://user-images.githubusercontent.com/62474734/188595532-550076e1-2cc1-4c92-85a0-4494d25ba7df.png)

**Comment by playingoDEERUX** [comment]
> "The fact that my implementation has an actual framework", ok and? this isnt some gt bot repository, just enet socks5 with simple enet client for gt
> 
> "My implementation has a very high-performance, extremely multithreaded, multi-clustered architecture", i dont see how this is lower performance than yours, could you show or tell proof about this?
> 
> "Lastly, my implementation actually works up-to-date because you will get shadowbans on THIS as opposed to mine because you dont visit the webserver before to 1. grab meta and 2. making a request to growtopia1.com/growtopia2.com is necessary to avoid shadowbans", this doesn't give shadow bans and uhh you can just make the https request with the same proxy if you want to.
> 
> * you are fucking weird, you said u quit gt and now writing some essays trying to prove you're the best, grow up...

i have uninstalled the actual game and everything and restrained from every related discord server, this is now just pure back-to-back provocation and has nothing to do with the game

**Comment by playingoDEERUX** [comment]
@AboodTBR when I released my enet socks5 + bot framework, which is totally in my right and no one has the right to take away what I do with my OWN stuff, I didn't start bashing out and calling out your names - instead when you published your stuff I instantly see my name again and a provocative text, do you really think im not gonna try to provocate back and say how much superior my work actually is? I wouldnt have needed to do this flexing if you didnt start provocation.
